# Generated by Django 4.0.1 on 2022-01-09 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouletteGame',
            fields=[
                ('gameID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('roulette_number', models.IntegerField()),
                ('player_limit', models.IntegerField()),
                ('dealerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealerID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouletteBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_number', models.IntegerField()),
                ('earning', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('dealerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer', to=settings.AUTH_USER_MODEL)),
                ('gameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='roulette.roulettegame')),
                ('playerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
