# Generated by Django 4.0.1 on 2022-01-10 09:57

from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0002_remove_roulettebet_earning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roulettegame',
            old_name='player_limit',
            new_name='bet_limit',
        ),
        migrations.RemoveField(
            model_name='roulettegame',
            name='roulette_number',
        ),
        migrations.AddField(
            model_name='roulettegame',
            name='amount_limit',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RouletteNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', encrypted_fields.fields.EncryptedIntegerField()),
                ('gameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GameID', to='roulette.roulettegame')),
            ],
        ),
    ]
