# Generated by Django 4.0.1 on 2022-01-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0003_rename_player_limit_roulettegame_bet_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roulettenumber',
            name='number',
            field=models.IntegerField(),
        ),
    ]
